### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by macjabeth** [dapetcu21/atom-autocomplete-lua#11]
Argument to `path.dirname` must be a string
```
Object.dirname (/opt/atom/resources/app.asar/src/electron-shims.js:9:10)
_loop (/home/bunster/.atom/packages/autocomplete-lua/lib/options/luacompleterc.js:57:41)
undefined.next (null:null:null)
LuaCompleteRcProvider.<anonymous> (/home/bunster/.atom/packages/autocomplete-lua/lib/options/luacompleterc.js:86:27)
undefined.next (null:null:null)
step (/home/bunster/.atom/packages/autocomplete-lua/lib/options/luacompleterc.js:7:273)
```

**Comment by dapetcu21** [comment]
Huh? Which one is it? Deprecated warning or argument must be a string? Also, what's your Atom version, plugin version and OS?

**Comment by macjabeth** [comment]
Atom Version: 1.14.2
Plugin Version: 0.8.0
OS: Linux (Ubuntu)

Not sure what the error was, it just showed up at the bottom and I clicked on the button to create an issue on here for it.

The deprecation error isn't showing up at the bottom anymore, though.

EDIT: Scratch that, it is showing up again.

![image](https://cloud.githubusercontent.com/assets/8473052/23198366/153bb8f8-f895-11e6-84d3-a276cfbe0577.png)

**Comment by THE-FYP** [comment]
same. appears after typing anything in editor with lua syntax.

**Comment by DanyGagnoon** [comment]
same

**Comment by pablomayobre** [comment]
This happens on new unsaved files, which haven't got a `path` associated to them so `path.dirname` gets `undefined` or `null` which of course aren't strings

**Comment by pablomayobre** [comment]
To expand. The problem is in [line 38 of luacompleterc.js](https://github.com/dapetcu21/atom-autocomplete-lua/blob/master/lib/options/luacompleterc.js#L38), in that line `path.dirname` is called with `filePath` as argument, which is defined above in [line 33](https://github.com/dapetcu21/atom-autocomplete-lua/blob/master/lib/options/luacompleterc.js#L33) as `editor.getBuffer().getPath()` which can return `null` on unsaved files.

I think that the `LuaCompleteRcProvider` should return the `previousOptions` if `filePath` is `null` as done [here](https://github.com/dapetcu21/atom-autocomplete-lua/blob/master/lib/options/luacompleterc.js#L58L60)
